### ISSUE TITLE
Submit scala-java-time to SP (Scala Platform)

### ISSUE THREAD

**Issue by mdedetrich** [cquiroz/scala-java-time#12]
With the SP process being announced (https://contributors.scala-lang.org/) I believe that there is a good argument for including scala-java-time into the Scala Platform as it would provide us with an idiomatic cross platform time/date library (and scala-java-time being in the SP would also help drive its adoption). A huge amount of work by @soc was put into making this library, and it would be a shame to see the work go to waste or not live up to its potential.

For the time being, these are the following changes that I would see as needing to be done before we submit (if its chosen to do so)

- Rename scala-java-time to something like scala-time, and put the library into a `scala.time` namespace
- Integrate MIMA to ensure binary compatibility
- Do any more changes to make the library more idiomatically Scala (if they exist) rather than being just a java.time clone
- Resolve any big, outstanding bugs
- Add in java converters to seamlessly go from `scala.time` types to  `java.time` (and vice versa) to make it painless for end users

**Comment by cquiroz** [comment]
This sounds like a good idea 👍  scala-time 3.0.0!

As a general comment, the internal code is very java-like (uses var, while loops, returns, etc) since it was mostly machine translated from threetenbp. I want to make it more scala idiomatic but a prerequisite in my opinion is to have a solid test suite before changing the guts

Feel free to make contributions but I will hold any changes to the internals until version 2.0.0 is ready with a solid test suite and supporting the last pieces missing (tz and Hijrah chrono)

**Comment by cquiroz** [comment]
I don’t think this is going to happen, closing...
