### ISSUE TITLE
any expected but <notype> found for tree of type org.scalajs.ir.Trees$Block

### ISSUE THREAD

**Issue by JackieDev** [cquiroz/scala-java-time#319]
Hi, I'm having an issue in scala-java-time/core/js/target/scala-3.0.0/src_managed/main/org/threeten/bp/format/**DateTimeFormatterBuilder**.scala(1536:4:Labeled)

The error given is: **any expected but <notype> found for tree of type org.scalajs.ir.Trees$Block**

Any ideas on how to solve this?

Using scala version 3.0.0
and version: 2.3.0 of this library

Thank you

**Comment by Cereopsis** [comment]
Out of interest, I have come across the same issue when compiling against `Scala 3.1.1 /ScalaJS 1.7.1` but everything works with `Scala 3.0.0/ScalaJS 1.5.1`

Haven't worked out what it is yet, the workaround for me at the moment is to not upgrade the project.

**Comment by mattyjbrown** [comment]
Got a minimal reproduction of the problem here. Problem seems to be with ScalaJS 1.7.1, as it works fine on ScalaJS 1.5.1 no matter the Scala version.

https://github.com/mattyjbrown/scalajs-minimal-repro

`git clone git@github.com:mattyjbrown/scalajs-minimal-repro.git && cd scalajs-minimal-repro && sbt fullOptJS`

**Comment by cquiroz** [comment]
Thanks,this is very useful. I think this maybe an issue upstream

**Comment by mattyjbrown** [comment]
Also opened with ScalaJS: https://github.com/scala-js/scala-js/issues/4601

**Comment by cquiroz** [comment]
Fixed upstream
